### ISSUE TITLE
escript is likely a build dependency

### ISSUE THREAD

**Issue by jeremiah** [PDXostc/rvi_core#60]
root@sylph:~/rvi_core# make ubuntu_package
./rebar clean
/usr/bin/env: escript: No such file or directory
Makefile:49: recipe for target 'clean' failed
make: *** [clean] Error 127

**Comment by mfeuer** [comment]
sudo apt-get Install erlang  python-jsonrpclib

Earlier versions of the RVI releases had the erlang VM built in, but we
moved that out so that we now depend on a pre-installed erlang VM.

I'll have that updated in the doc.

/Magnus F.

-------------------

*Head System Architect - Open Source Projects**Jaguar Land Rover*

*Email*: mfeuer@jaguarlandrover.com
*Mobile*: +1 949 294 7871



Jaguar Land Rover North America, LLC
1419 NW 14th Ave, Portland, OR 97209
-------------------
Business Details:
Jaguar Land Rover Limited
Registered Office: Abbey Road, Whitley, Coventry CV3 4LF
Registered in England No: 1672070

This e-mail and any attachments contain confidential information for a
specific individual and purpose.  The information is private and privileged
and intended solely for the use of the individual to whom it is addressed.
If you are not the intended recipient, please e-mail us immediately.  We
apologise for any inconvenience caused but you are hereby notified that any
disclosure, copying or distribution or the taking of any action in reliance
on the information contained herein is strictly prohibited.

This e-mail does not constitute an order for goods or services unless
accompanied by an official purchase order.

**Comment by jeremiah** [comment]
I'm working on the BUILD.md doc adding how to build for Debian Jessie. Debian contains erlang 1:17.3-dfsg-4 and escript tooling. Debian also contains rebar and a tool called dh_rebar which helps build erlang packages that use rebar. I'm going to experiment with that.

**Comment by jeremiah** [comment]
Closing this because I believe that escript is in the erlang package in Debian and erlang likely has to be a build dependency.

**Comment by mfeuer** [comment]
Ok. Please note that RVI is only tested with Erlang R16B03, although it should work with R17 as well.
