### ISSUE TITLE
rebar compile error

### ISSUE THREAD

**Issue by jeremiah** [PDXostc/rvi_core#62]
Hi,

I'm trying to build rvi_core from source. I get this error;

./rebar  compile
==> lager (compile)
==> src (compile)
==> exo (compile)
==> edown (compile)
/home/jeremiah/rvi-core-0.4.0/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/home/jeremiah/rvi-core-0.4.0/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
ERROR: compile failed while processing /home/jeremiah/rvi-core-0.4.0/deps/edown: rebar_abort
Makefile:43: recipe for target 'compile' failed
make: *** [compile] Error 1

**Comment by jeremiah** [comment]
Here's some debugging info;

DEBUG: Worker compilation failed: [{error,
                                    {error,
                                     [["/home/jeremiah/rvi-core-0.4.0/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen\n",
                                       "/home/jeremiah/rvi-core-0.4.0/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen\n"]],
                                     []}},
                                   {source,"src/edown_doclet.erl"}]

**Comment by mfeuer** [comment]
Which erlang version are you using when building?
Also - Trying to reach you on IRC.

**Comment by uwiger** [comment]
This error occurs if you try to build rvi_core with OTP 18.

The current version of rvi_core is tested on R16B03-1.

If you absolutely want to build rvi_core with OTP 18, you *may* be successful doing the following:
```shell
$ cd ..../rvi_core
$ rm -rf deps/edown
$ rebar get-deps
$ make
```

(... but no promises. It should at least fix the edown issue.)

Our intention is to move to OTP 18 in rvi_core 0.5.0.

**Comment by jeremiah** [comment]
What is OTP? If I know what it is I can look for it in the Debian / Ubuntu archives. Otherwise I may wait for 0.5.0.

**Comment by uwiger** [comment]
OTP = Open Telecom Platform (yeah, I know), is the Erlang middleware - what you find on https://github.com/erlang/otp

I believe it would correspond to something linke erlang_*_all.deb

This seems to be a complete Erlang 18.1 package:
http://pkgs.org/debian-sid/debian-main-i386/erlang_18.1-dfsg-1_all.deb.html

The version in the Jessie version seems to be 17.3.

Otherwise, https://packages.erlang-solutions.com/erlang/#tabs-debian should offer the most complete list of tested Erlang versions (and commercially supported, if that matters to you).

**Comment by jeremiah** [comment]
Thanks very much Ulf, this is helpful. (Jag tror att jag faktiskt kikade på OTP när jag jobbade för Ericsson i 2008. :)
